guests = ['dana', 'jeff', 'ana', 'ellie']
print(f'Would you like to come to dinner {guests[0].title()}?')
print(f'Would you like to come to dinner {guests[1].title()}?')
print(f'Would you like to come to dinner {guests[2].title()}?')
print(f'Would you like to come to dinner {guests[3].title()}?')
print('We found a table with three more spots!')
guests.insert(0, 'lily')
guests.insert(3, 'carly')
guests.append('harper')
print(f'Would you like to come to dinner {guests[0].title()}?')
print(f'Would you like to come to dinner {guests[1].title()}?')
print(f'Would you like to come to dinner {guests[2].title()}?')
print(f'Would you like to come to dinner {guests[3].title()}?')
print(f'Would you like to come to dinner {guests[4].title()}?')
print(f'Would you like to come to dinner {guests[5].title()}?')
print(f'Would you like to come to dinner {guests[6].title()}?')